@FixFlow.API_HostAddress = http://localhost:5253
@customerToken = PUT_CUSTOMER_TOKEN_HERE
@adminToken =PUT_adminToken_TOKEN_HERE
@technicianToken = PUT_technicianToken_TOKEN_HERE
GET {{FixFlow.API_HostAddress}}/api/categories
Accept: application/json

###

POST {{FixFlow.API_HostAddress}}/api/maintenance-requests
Content-Type: application/json
X-Customer-Id: customer-1

{
  "title": "AC is not working",
  "description": "The air conditioner turns on but does not cool the room.",
  "serviceCategoryId": "a1fc575d-c11a-4362-84a2-96429d68cbe0",
  "location": "Building A - Room 203",
  "preferredDate": "2026-07-15T14:00:00"
}

###

GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/my-requests
X-Customer-Id: customer-1
Accept: application/json

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572/assign-technician
Content-Type: application/json

{
  "technicianId": "technician-1"
}

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572/accept
X-Technician-Id: technician-1

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572/start-work
X-Technician-Id: technician-1

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572/complete
X-Technician-Id: technician-1

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572/confirm
X-Customer-Id: customer-1

###
/////////////////////////////////
GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/my-assigned
X-Technician-Id: technician-1
Accept: application/json

###

GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572
X-Technician-Id: technician-1
Accept: application/json

###

GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572
X-Customer-Id: customer-2
Accept: application/json
###
GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/0a8c50ce-96ee-4f1c-a344-22f503a6b572
X-Customer-Id: customer-2
Accept: application/json



###

POST {{FixFlow.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Customer One",
  "email": "customer1@test.com",
  "password": "Test123",
  "role": "Customer"
}
////////////////////////////////////////
###

POST {{FixFlow.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "customer1@test.com",
  "password": "Test123"
}
/////////////////////////////////
###

POST {{FixFlow.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Technician One",
  "email": "technician1@test.com",
  "password": "Test123",
  "role": "Technician"
}





###
  POST {{FixFlow.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "customer20@test.com",
  "password": "Test2300"
}

###
@FixFlow.API_HostAddress = https://localhost:7153
@customerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA3OTc1MDRjLWNkNzctNDk4ZC1iNjYwLWNjMmFhOTExY2FmOCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJjdXN0b21lcjFAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjdXN0b21lcjFAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJDdXN0b21lciIsImV4cCI6MTc4Mzk0NjcxOCwiaXNzIjoiRml4RmxvdyIsImF1ZCI6IkZpeEZsb3dVc2VycyJ9.j0neHS2WvKM847AW-zmNLsFDJ6cRvZjj5WA0yVCI4pg
###

POST {{FixFlow.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "customer1@test.com",
  "password": "Test123"
}



###

GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/my-requests
Authorization: Bearer {{customerToken}}
Accept: application/json




###

POST {{FixFlow.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Admin Two",
  "email": "admin2@test.com",
  "password": "Test123",
  "role": "Admin"
}

###

POST {{FixFlow.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "technician1@test.com",
  "password": "Test123"
}


###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/57c467a0-0884-49f9-add8-9d9d29d6356d/accept
Authorization: Bearer {{technicianToken}}

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/57c467a0-0884-49f9-add8-9d9d29d6356d/start-work
Authorization: Bearer {{technicianToken}}

  ###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/57c467a0-0884-49f9-add8-9d9d29d6356d/complete
Authorization: Bearer {{technicianToken}}

###

PUT {{FixFlow.API_HostAddress}}/api/maintenance-requests/57c467a0-0884-49f9-add8-9d9d29d6356d/confirm
Authorization: Bearer {{customerToken}}


###

GET {{FixFlow.API_HostAddress}}/api/maintenance-requests/my-requests
Authorization: Bearer {{customerToken}}
Accept: application/json